### ISSUE TITLE
Derivatives page 404

### ISSUE THREAD

**Issue by sophiazhu16** [socrathematics/socrathematics.github.io#19]
**Describe the bug**
Cannot go to derivatives page from limits definition page.

**To Reproduce**
1. Go to https://socrathematics.github.io/calculus/limits/definition/
2. Click on 'Derivatives'
3. See 404 error

**Expected behavior**
No 404 error. Should go to Derivatives page, which exists.

**Comment by saumyasinghal747** [comment]
fix it!

**Comment by saumyasinghal747** [comment]
If you're going to close an issue, link a pull request to it that solves the problem.

**Comment by sophiazhu16** [comment]
I forgot which pull request it was :(
I think I committed directly to the master branch.
