### ISSUE TITLE
Homepage thumbnail photos need personalization

### ISSUE THREAD

**Issue by saumyasinghal747** [socrathematics/socrathematics.github.io#2]
Photos representing Mod, Trig, and Calc are taken from outside sources may be copyrighted and we must replace them

**Comment by socrathematics** [comment]
Still need images for modular arithmetic and calc. Please title the pull request with the photo's course name  + "photo".

**Comment by socrathematics** [comment]
Now we need an image for exponents. **_Make sure they maintain thee previous height:width ratio!!!_**

**Comment by saumyasinghal747** [comment]
Still need exponents, replace mod with exponents
